/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VirtualPetProject;

import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author zenox
 */
public class LoadPet extends javax.swing.JFrame {
    
    private final List<Animal> existingPets;
    
    /**
     * Creates new form LoadPet
     * @param existingPets
     */
    
    
    public LoadPet(List<Animal> existingPets) {
        this.existingPets = existingPets;
        initComponents();
        populatePetNames();
    }
    
    private void populatePetNames() {
        for (Animal pet : existingPets) {
            jComboBox1.addItem(pet.getPetName() + " (" + getType(pet) + ")");
        }
    }
    
    private String getType(Animal pet) {
        String type = "";
        if (pet instanceof Dog) {
            type = "Dog";
        } else if (pet instanceof Cat) {
            type = "Cat";
        }
        return type;
    }
    
    private Animal findPetByNameAndType(String nameAndType) {
        // Extract pet name from the combo box item (name(type))
        String petName = nameAndType.split("\\(")[0].trim();

        // Extract pet type from the combo box item (name(type))
        String petType = nameAndType.split("\\(")[1].replace(")", "").trim();

        // Find the pet by name and type
        for (Animal pet : existingPets) {
            if (pet.getPetName().equals(petName) && getType(pet).equals(petType)) {
                return pet;
            }
        }
        return null; // Pet not found
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Load existing pet");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("PLAY!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(339, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(316, 316, 316))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(338, 338, 338))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(370, 370, 370))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(jButton1)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String selectedPetName = (String) jComboBox1.getSelectedItem();
        if (selectedPetName != null) {
            Animal selectedPet = findPetByNameAndType(selectedPetName);
            if (selectedPet != null) {
                // Proceed with the selected pet (selectedPet)
                GameplayGUI gameplayGUI1 = new GameplayGUI(selectedPet);
                gameplayGUI1.show();
        
                dispose(); // Close the current frame
            } else {
                JOptionPane.showMessageDialog(this, "Error loading selected pet.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a pet.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
